# This is a basic build and deploy workflow for internal applications
name: Build and Deploy
env:
  CF_API_KEY: ${{ secrets.CODEFRESH_API_TOKEN }}
  CFVAR_API_TOKEN: ${{ secrets.API_TOKEN }}
  CFVAR_POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
  CFVAR_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  CFVAR_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  CFVAR_HELM_CHART_NAME: tap
  CFVAR_HELM_CHART_VERSION: 0.0.1
on: 
  push:
    branches-ignore:
      - 'master'
  pull_request:
    types: [closed]
    branches:
      - master
  release:
    types: [published]
    branches:
      - master
jobs:
  # build:
  #   if: github.ref != 'master' && github.event_name == 'push'
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Trigger internal apps build pipeline
  #     uses: soxhub/codefresh-pipeline-runner@codefresh-run-variables
  #     env:
  #       PIPELINE_ID: '5e9b7165c2b7b02672c11e51'
  #     id: build
  deploy:
    runs-on: ubuntu-latest
    # if: github.event_name == 'pull_request' && github.base_ref == 'master'
    steps:
    - name: Trigger internal apps tap pipeline
      uses: soxhub/codefresh-pipeline-runner@codefresh-run-variables
      env:
        PIPELINE_ID: '5eab1603c258c73d6a1f7722'
        CFVAR_API_TOKEN: ${{ secrets.API_TOKEN }}
      id: deploy
